language: generic
services:
  - docker

sudo: true

cache:
  directories:
    - .nginx

before_install:
  - docker pull ubuntu:18.04
  - docker pull ubuntu:16.04

script: 
  - docker run --rm -it -v $(pwd):/ci ubuntu:18.04 bash -c "cd /ci; ./install.sh"
