language: bash
services:
  - docker

sudo: true

cache:
  directories:
    - .nginx

matrix:
  include:
    - name: "Ubuntu 18.04"
      env: DISTRO=ubuntu:18.04
    - name: "Ubuntu 16.04"
      env: DISTRO=ubuntu:16.04

before_install:
  - docker pull ${DISTRO}
script: 
  - docker run --rm -it -w "/ci" -v $(pwd):/ci ${DISTRO} bash -c "./install.sh"
